name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.302'  # 指定具体的 .NET SDK 版本

    - name: Restore dependencies
      working-directory: src/Y2Downloader  # 设置工作目录为项目的根目录
      run: dotnet restore

    - name: Build
      working-directory: src/Y2Downloader  # 设置工作目录为项目的根目录
      run: dotnet build --configuration Release --no-restore

    - name: Test
      working-directory: src/Y2Downloader  # 设置工作目录为项目的根目录
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Upload build artifacts
      if: success()  # 仅在构建成功后上传工件
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          src/Y2Downloader  # 指定要上传的文件或目录路径
